In [1]:
import pandas as pd

In [2]:
#importando dados
df = pd.read_csv(r"C:\Users\joaoe.DESKTOP-53TM428\OneDrive\Documents\Pandas\Pratica_Dados\dados_funcionarios.csv")
print(df.head())

   id   nome  idade          cidade          profissao  salario  \
0   1   João     56  Rio de Janeiro          Motorista  2339.72
1   2   João     36       Fortaleza      Administrador  3618.52
2   3   João     53        Brasília           Designer  3471.10
3   4  Maria     47       Fortaleza  Analista de Dados  1884.98
4   5   João     38       Fortaleza      Administrador  4754.85

   anos_experiencia data_contratacao  avaliacao
0                31       2023-12-02       3.39
1                12       2022-11-27       2.84
2                31       2024-02-09       3.89
3                24       2023-01-21       1.73
4                12       2023-07-15       3.10

In [3]:
df_infor = df.info()
df_infor

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                500 non-null    int64
 1   nome              500 non-null    str
 2   idade             500 non-null    int64
 3   cidade            500 non-null    str
 4   profissao         500 non-null    str
 5   salario           500 non-null    float64
 6   anos_experiencia  500 non-null    int64
 7   data_contratacao  500 non-null    str
 8   avaliacao         500 non-null    float64
dtypes: float64(2), int64(3), str(4)
memory usage: 35.3 KB

In [4]:
#2-Analise basica (Média de salário)
df_media =df["salario"].mean().astype(int)
print(df_media)

3024

In [5]:
#3-Analise basica (Média por Profissão)
df_media_profissao =df.groupby("profissao")["salario"].mean().astype(int)

print(df_media_profissao)

profissao
Administrador        2865
Analista de Dados    2851
Desenvolvedor        3147
Designer             3052
Enfermeiro           3125
Motorista            3088
Professor            3036
Vendedor             2972
Name: salario, dtype: int64

In [6]:
#4-Quantidade de pessoas por cidade
df_quantidade_cidade = df["cidade"].value_counts()
df_quantidade_cidade

cidade
Timon             71
Recife            61
Rio de Janeiro    55
Fortaleza         55
Salvador          54
São Luís          53
Teresina          53
Brasília          51
São Paulo         47
Name: count, dtype: int64

In [7]:
#5 - Filtros 1 (Pessoas com salario acima de 5000)
df_filtro_1 = df[df["salario"] > 5000][["nome","profissao","salario"]]
df_filtro_1

         nome          profissao  salario
9     Mariana           Designer  5222.73
22     Rafael      Desenvolvedor  7046.76
30     Carlos         Enfermeiro  5334.14
74      Lucas         Enfermeiro  5546.59
77   Fernanda          Motorista  5246.41
94        Ana      Desenvolvedor  5294.78
112  Fernanda           Designer  5627.76
117   Juliana      Administrador  5197.75
121       Ana         Enfermeiro  5293.84
127   Juliana           Designer  6047.11
155     Lucas      Desenvolvedor  6140.04
158     Lucas      Desenvolvedor  5396.41
159   Juliana          Motorista  5380.79
195   Mariana      Desenvolvedor  5181.62
205   Juliana           Vendedor  5117.62
222  Fernanda           Vendedor  6072.10
251    Carlos          Motorista  6800.85
253  Fernanda         Enfermeiro  5155.05
271       Ana          Professor  5292.97
297     Maria  Analista de Dados  5371.85
360     Lucas         Enfermeiro  5006.74
393  Fernanda           Vendedor  5746.42
404      João  Analista de Dados  5588.77
464      João          Motorista  5608.49

In [8]:
#5- Filtro 2 (Pessoas com mais de 10 anos de experiencia)
df_experiencia = df[df["anos_experiencia"] > 10] [["nome","profissao","anos_experiencia"]] 
print(df_experiencia)

         nome          profissao  anos_experiencia
0        João          Motorista                31
1        João      Administrador                12
2        João           Designer                31
3       Maria  Analista de Dados                24
4        João      Administrador                12
..        ...                ...               ...
492     Lucas           Vendedor                24
493     Lucas           Designer                20
494      João      Administrador                29
497    Rafael  Analista de Dados                20
498  Fernanda          Motorista                35

[328 rows x 3 columns]

In [9]:
#5- Filtro 3( Quantidade de Pessoas por Profissão)

df_pessoas_por_profissao = df.groupby("profissao").size().reset_index(name="quantidade")
print(df_pessoas_por_profissao)

           profissao  quantidade
0      Administrador          51
1  Analista de Dados          58
2      Desenvolvedor          68
3           Designer          54
4         Enfermeiro          69
5          Motorista          68
6          Professor          59
7           Vendedor          73

In [10]:
#6 - Ordenação 1- Colocando em ordem do maior salario ao menor por ordem alfabetica)
df_odernacao_1 = df.sort_values(by=["nome","salario"],ascending=[True,False])[["nome","salario"]]
df_odernacao_1

       nome  salario
94      Ana  5294.78
121     Ana  5293.84
271     Ana  5292.97
338     Ana  4970.42
301     Ana  4251.32
..      ...      ...
79   Rafael  1283.83
118  Rafael  1200.00
217  Rafael  1200.00
367  Rafael  1200.00
368  Rafael  1200.00

[500 rows x 2 columns]

In [11]:
#6 - Ordenação 2-Colocando em ordem quem tem mais experiencia mostrando o nome e profissao e o tempo de experiencia
df_odernacao_2 = df.sort_values(by="anos_experiencia",ascending=False)[["nome","profissao","anos_experiencia"]]
df_odernacao_2

         nome          profissao  anos_experiencia
170       Ana      Desenvolvedor                41
250      João  Analista de Dados                41
361     Pedro          Motorista                40
291    Carlos      Administrador                40
308   Mariana      Administrador                40
..        ...                ...               ...
117   Juliana      Administrador                 0
449   Juliana         Enfermeiro                 0
448  Fernanda          Professor                 0
6     Juliana         Enfermeiro                 0
476      João           Designer                 0

[500 rows x 3 columns]

In [12]:
#7 Juntando Tudo Filtrar, Arupar e Ordenar,
# Grupo de pessoa na empresa que recebe  ate 3000 e argupar por profissao em ordem alfabetica

grupo1 = df[df["salario"] <= 3000][["nome","profissao","salario"]].sort_values(by="nome")
grupo1

       nome          profissao  salario
262     Ana         Enfermeiro  2220.97
315     Ana         Enfermeiro  2887.48
309     Ana  Analista de Dados  1200.00
293     Ana  Analista de Dados  1825.48
290     Ana           Vendedor  2734.84
..      ...                ...      ...
431  Rafael         Enfermeiro  2475.05
254  Rafael          Professor  2917.17
76   Rafael          Motorista  2715.13
405  Rafael      Desenvolvedor  2273.14
38   Rafael         Enfermeiro  2407.88

[256 rows x 3 columns]

In [13]:
#7 Juntando Tudo Filtrar, Arupar e Ordenar,
# A media de cidade que paga mais em cada profissão
df_cidade_paga_med = df.groupby(["cidade","profissao"]) ["salario"].mean().astype(int).reset_index().sort_values(by=["profissao","salario"],ascending=[True,False]).drop_duplicates(subset="profissao").drop_duplicates(subset="cidade")
print("Media de cidades")
print("---------------------------------")
print(df_cidade_paga_med)
df_cidade_paga_max = df.groupby(["cidade","profissao"]) ["salario"].max().astype(int).reset_index().sort_values(by=["profissao","salario"],ascending=[True,False]).drop_duplicates(subset="profissao").drop_duplicates(subset="cidade")
print("---------------------------------")
print("Cidade que paga mais ")
print("---------------------------------")
print(df_cidade_paga_max)
print("---------------------------------")
print("Cidade que paga menos")
print("---------------------------------")
df_cidade_paga_mix = df.groupby(["cidade","profissao"]) ["salario"].min().astype(int).reset_index().sort_values(by=["profissao","salario"],ascending=[True,False]).drop_duplicates(subset="profissao").drop_duplicates(subset="cidade")
print(df_cidade_paga_mix)
print("---------------------------------")

Media de cidades
---------------------------------
       cidade          profissao  salario
8   Fortaleza      Administrador     3658
17     Recife  Analista de Dados     3285
3    Brasília           Designer     3935
52  São Paulo         Enfermeiro     3814
69      Timon          Motorista     3801
47   São Luís           Vendedor     3761
---------------------------------
Cidade que paga mais
---------------------------------
       cidade          profissao  salario
64      Timon      Administrador     5197
1    Brasília  Analista de Dados     5588
50  São Paulo      Desenvolvedor     7046
---------------------------------
Cidade que paga menos
---------------------------------
            cidade          profissao  salario
24  Rio de Janeiro      Administrador     2819
17          Recife  Analista de Dados     2137
42        São Luís      Desenvolvedor     2454
59        Teresina           Designer     3249
5         Brasília          Motorista     2173
14       Fortaleza          Professor     2769
---------------------------------

In [ ]:
# Criando arquivo csv 
df.to_excel(r"C:\Users\joaoe.DESKTOP-53TM428\OneDrive\Documents\Pandas\Pratica_Dados\dados_Teste.xlsx",index=False)