In [104]:
import pandas as pd

In [105]:
df = pd.read_json(r"C:\Users\joaoe.DESKTOP-53TM428\OneDrive\Documents\Pandas\Estudos\receitas.json",encoding="utf-8")
df

                                            receitas
0  {'titulo': 'Bolo de Chocolate', 'tempo_preparo...
1  {'titulo': 'Salada Caesar', 'tempo_preparo': '...
2  {'titulo': 'Pasta ao Pesto', 'tempo_preparo': ...

In [103]:
df_receitas = pd.json_normalize(
    df['receitas'],
    'ingredientes',   
    ['titulo','tempo_preparo','porcoes']
)

In [106]:
df_receitas

         ingrediente  quantidade             titulo tempo_preparo porcoes
0   Farinha de Trigo   2 xícaras  Bolo de Chocolate    45 minutos       8
0             Açúcar    1 xícara  Bolo de Chocolate    45 minutos       8
0               Ovos   3 xícaras  Bolo de Chocolate    45 minutos       8
0              Leite    1 xícara  Bolo de Chocolate    45 minutos       8
0           Manteiga  1/2 xícara  Bolo de Chocolate    45 minutos       8
1      Alface romana    1 cabeça      Salada Caesar    20 minutos       4
1           Croutons    1 xícara      Salada Caesar    20 minutos       4
1    Queijo parmesão  1/2 xícara      Salada Caesar    20 minutos       4
1       Molho caesar  1/4 xícara      Salada Caesar    20 minutos       4
2              Massa        200g     Pasta ao Pesto    30 minutos       2
2  Manjericão fresco  1/2 xícara     Pasta ao Pesto    30 minutos       2
2    Azeite de oliva  1/3 xícara     Pasta ao Pesto    30 minutos       2
2              Nozes  1/4 xícara     Pasta ao Pesto    30 minutos       2
2    Queijo parmesão  1/4 xícara     Pasta ao Pesto    30 minutos       2