In [1]:
import pandas as pd

In [3]:
df_produtos = pd.read_csv("dados/ecommerce_user_behavior_8000.csv")
df_produtos

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
0,1.0,56.0,Female,Desktop,12.90,8.0,13.0,1.0,1.0,NaN,0.0,6.97,28.18,1.0
1,2.0,46.0,Male,Mobile,15.63,9.0,4.0,6.0,1.0,1.0,1.0,19.17,86.73,1.0
2,3.0,32.0,Female,NaN,11.64,12.0,11.0,0.0,0.0,0.0,1.0,8.87,83.09,1.0
3,4.0,25.0,Female,Mobile,22.71,5.0,10.0,1.0,0.0,0.0,1.0,NaN,79.03,1.0
4,5.0,38.0,Female,Mobile,26.35,9.0,12.0,4.0,1.0,0.0,0.0,18.15,55.35,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996.0,48.0,Female,Tablet,2.67,10.0,6.0,0.0,1.0,0.0,1.0,3.01,82.44,1.0
7996,7997.0,54.0,Male,Mobile,18.94,13.0,11.0,4.0,1.0,1.0,1.0,27.48,10.06,1.0
7997,7998.0,54.0,Female,Desktop,24.08,8.0,13.0,1.0,0.0,0.0,1.0,27.57,21.34,1.0
7998,7999.0,32.0,Female,Mobile,10.85,13.0,12.0,8.0,1.0,1.0,0.0,5.78,2.03,1.0
7999,8000.0,46.0,Female,Mobile,12.23,2.0,9.0,2.0,0.0,1.0,1.0,8.28,15.67,1.0

In [5]:
df_produtos.dtypes

user_id               float64
age                   float64
gender                    str
device_type               str
time_on_site          float64
pages_viewed          float64
previous_purchases    float64
cart_items            float64
discount_seen         float64
ad_clicked            float64
returning_user        float64
avg_session_time      float64
bounce_rate           float64
purchase              float64
dtype: object

In [6]:
df_produtos['cart_items'] = pd.to_numeric(df_produtos['cart_items'])
df_produtos['discount_seen'] = pd.to_numeric(df_produtos['discount_seen'])

In [8]:
#1-Desempenho de vendas por Categoria
vendas_categoria = df_produtos.groupby('device_type')['cart_items'].sum()
vendas_categoria

device_type
Desktop    10499.0
Mobile     20832.0
Tablet      3497.0
Name: cart_items, dtype: float64

In [10]:
#2-Produto mais vendido
produto_mais_vendido = df_produtos.groupby('device_type')['cart_items'].sum().idxmax()
produto_mais_vendido

'Mobile'

In [11]:
#3-Preço Médio por Produto
media_preco_produto = df_produtos.groupby('device_type')['time_on_site'].mean()
media_preco_produto

device_type
Desktop    15.490938
Mobile     15.807614
Tablet     15.956632
Name: time_on_site, dtype: float64

In [13]:
#5-correlação entre unidades vendidas e preço Unitário
correlacao = df_produtos['cart_items'].corr(df_produtos['ad_clicked'])
print(correlacao)

-0.0075930681336941865

In [15]:
vendas_categoria_df = vendas_categoria.reset_index()
vendas_categoria_df_columms = ['device_type','cart_items']

In [16]:
vendas_categoria_df

   index device_type  cart_items
0      0     Desktop     10499.0
1      1      Mobile     20832.0
2      2      Tablet      3497.0

In [17]:
vendas_categoria_df.to_csv("dados/vendas_categoria.csv",index=False)