In [10]:
import pandas as pd

In [11]:
df = pd.read_excel("dados/campeonato.xlsx")
df

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
0,Palmeiras,10,9,3,2,18,12,6,30
1,Flamengo,10,7,2,1,22,10,12,23
2,Corintinhas,10,6,3,3,14,16,-2,21
3,São Paulo,10,4,1,3,16,15,1,13
4,Santos,10,3,2,5,10,20,-10,11

In [12]:
df.dtypes

Times                 str
Partidas_Jogadas    int64
Vitorias            int64
Empates             int64
Derrotas            int64
Gols_Pro            int64
Gols_Contra         int64
Saldo_Gols          int64
Pontos              int64
dtype: object

In [13]:
df.describe()

,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
count,5.0,5.000000,5.00000,5.00000,5.000000,5.000000,5.000000,5.000000
mean,10.0,5.800000,2.20000,2.80000,16.000000,14.600000,1.400000,19.600000
std,0.0,2.387467,0.83666,1.48324,4.472136,3.847077,8.294577,7.733046
min,10.0,3.000000,1.00000,1.00000,10.000000,10.000000,-10.000000,11.000000
25%,10.0,4.000000,2.00000,2.00000,14.000000,12.000000,-2.000000,13.000000
50%,10.0,6.000000,2.00000,3.00000,16.000000,15.000000,1.000000,21.000000
75%,10.0,7.000000,3.00000,3.00000,18.000000,16.000000,6.000000,23.000000
max,10.0,9.000000,3.00000,5.00000,22.000000,20.000000,12.000000,30.000000

In [14]:
df.head(4)

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
0,Palmeiras,10,9,3,2,18,12,6,30
1,Flamengo,10,7,2,1,22,10,12,23
2,Corintinhas,10,6,3,3,14,16,-2,21
3,São Paulo,10,4,1,3,16,15,1,13

In [8]:
df.tail(4)

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
1,Flamengo,10,7,2,1,22,10,12,23
2,Corintinhas,10,6,3,3,14,16,-2,21
3,São Paulo,10,4,1,3,16,15,1,13
4,Santos,10,3,2,5,10,20,-10,11

In [16]:
#1 - Analise de Desempenho por Time
desempenho_info = df[['Times','Pontos','Vitorias','Saldo_Gols']].set_index('Times')
desempenho_info

             Pontos  Vitorias  Saldo_Gols
Times
Palmeiras        30         9           6
Flamengo         23         7          12
Corintinhas      21         6          -2
São Paulo        13         4           1
Santos           11         3         -10

In [18]:
#2-Time com  menos vitorias
times_menos_vitorias = df[df['Vitorias'] == df['Vitorias'].min()]
times_menos_vitorias

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
4,Santos,10,3,2,5,10,20,-10,11

In [19]:
#3-Distribuição de Gols Pró
df['Gols_Pro'].value_counts()

Gols_Pro
18    1
22    1
14    1
16    1
10    1
Name: count, dtype: int64

In [22]:
#4-Relação entre gols pró e contras
correlacao = df['Gols_Pro'].corr(df['Pontos'])
print(correlacao)

0.6506042984620202